### ISSUE TITLE
Appointment functionality doesn't use an MVC approach

### ISSUE THREAD

**Issue by FedorGabrus** [FedorGabrus/TAFE19S204#2]
Appointment functionality doesn't use an MVC approach. Consider moving logic from View to Model.

**Comment by chrisT-pixel** [comment]
Hi Fedor,

What do you suggest I move over to viewModels?  The logic for appointments seems similar to other features in the app (assets, debts, etc) and they all use xaml with code behind (.cs) to handle logic. Can you please provide an example of one of the other features and how they work with the viewModel?

**Comment by FedorGabrus** [comment]
# App layers
## When using the MVVM pattern, an app is divided into the following layers:
* The **model** layer defines the types that represent your business data. This includes everything required to model the core app domain, and often includes core app logic. This layer is completely independent of the view and view-model layers, and often resides partially in the cloud. Given a fully implemented model layer, you can create multiple different client apps if you so choose, such as UWP and web apps that work with the same underlying data.
* The **view** layer defines the UI using XAML markup. The markup includes data binding expressions (such as x:Bind) that define the connection between specific UI components and various view-model and model members. Code-behind files are sometimes used as part of the view layer to contain additional code needed to customize or manipulate the UI, or to extract data from event handler arguments before calling a view-model method that performs the work.
* The **view-model** layer provides data binding targets for the view. In many cases, the view-model exposes the model directly, or provides members that wrap specific model members. The view-model can also define members for keeping track of data that is relevant to the UI but not to the model, such as the display order of a list of items. The view-model also serves as an integration point with other services such as database-access code. For simple projects, you might not need a separate model layer, but only a view-model that encapsulates all the data you need.

[Data binding and MVVM](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-and-mvvm)

**Comment by chrisT-pixel** [comment]
Hi Fedor,

Thanks for the information above.

I feel we should use the same logic pattern as the features already created in the app so I don't recommend adding this MVVM pattern. I have added the appropriate label
