### ISSUE TITLE
Current build doesn't work in Visual Studio 2016

### ISSUE THREAD

**Issue by FedorGabrus** [FedorGabrus/TAFE19S204#5]
Current build in master doesn't work in Visual Studio 2015. 
After this fix is implemented, all new merges should be tested in VS 2105.

**Comment by FedorGabrus** [comment]
Should be fixed by Personal Info brunch merge.

**Comment by chrisT-pixel** [comment]
cheers Fedor,

Let me know if I can provide assistance

**Comment by FedorGabrus** [comment]
Looks like it works Ok now
